stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - src/prepare.py
    params:
    - prepare.seed
    - prepare.shuffle
    - prepare.split
    - prepare.stratify
    outs:
    - data/processed
